// game/render/overlay_ground_gt3gt4.h — PC-native bodies for the A00-overlay GROUND/SCENE
// GT3/GT4 render-packet emitter pair (FUN_8013FB88 = GT3, FUN_8013FE58 = GT4) and their shared
// per-object entity-loop caller (FUN_801401B8). See overlay_ground_gt3gt4.cpp for the full RE
// trace.
//
// WIRED + SBS-gated (frontier, 2026-07-08). Was UNWIRED/UNVERIFIED draft banked ahead of the
// frontier (docs/engine_re.md region-map session); this session re-diffed entityLoop against
// ground truth (authenticated executable/overlay evidence overlay guest 0x801401B8), found + fixed a real bug (a
// spurious extra pointer dereference on the ground-record table — see .cpp), MIRRORED
// entityLoop's own real 40-byte guest-stack frame (was the one honest, explicitly-flagged gap;
// gt3/gt4's frames were already mirrored), and registered all three via A00 tomba::native::declareOverride.
//
// Sibling of the ALREADY-OWNED (game/render/overlay_gt3gt4.{h,cpp}) FIELD-OBJECT GT3/GT4 emitter
// (FUN_801465EC/801467BC) — docs/engine_re.md ("Deferred render pipeline" + "GAME-STAGE OBJECT
// PIPELINE" step 7) documents these as the OTHER copy: "the ground/scene entities go
// 0x8003D0BC -> 0x801401B8 (entity loop) -> 0x8013FE58/0x8013FB88 (overlay GT4/GT3 submitters)".
// Same shape (GTE RTPT/RTPS + NCLIP + AVSZ3/4-or-custom-blend into the shared packet-pool bump
// allocator + OT linked list), but NOT byte-identical to the field pair — see .cpp for the
// concrete differences (colour mask, byte-packed header counts, 3-way min/max Z-select instead
// of the pairwise-clamp chain).
//
// Copies: A02 0x801246A4/0x8012496C and A07 0x8012C7E0/0x8012CAA8 pick the farthest SZ for flag mode 2
// too; A0L 0x8010AA4C/0x8010AD40 does as well and adds kModeBias to GT3's mode 1 and GT4's mode 2.
#pragma once
#include <cstdint>

struct Core;
class Game;

class OverlayGroundGt3Gt4 {
public:
  // Flag modes 1 and 2 (flag & 3) pick the farthest SZ, or the nearest for mode 2 when `modeTwoNearest`;
  // `biasedMode` names the mode whose depth gets kModeBias (0 for none).
  struct ListDepth {
    bool modeTwoNearest;
    std::uint32_t biasedMode;
  };
  struct Variant {
    ListDepth gt3;
    ListDepth gt4;
  };
  static constexpr std::int32_t kModeBias = 0x64;
  static constexpr Variant kA00{{true, 0u}, {true, 0u}};
  static constexpr Variant kFarthest{{false, 0u}, {false, 0u}};
  static constexpr Variant kA0L{{false, 1u}, {false, 2u}};

  // FUN_8013FB88/FUN_8013FE58(rec=a0, ot_base=a1, count=a2) -> advanced rec ptr in v0
  static void gt3(Core *c, const ListDepth &depth);
  static void gt4(Core *c, const ListDepth &depth);
  static void entityLoop(Core *c); // FUN_801401B8(list=a0) -> loads camera GTE ctrl regs 0..7 from
                                   // 0x1F8000F8, then walks list's u16 index array calling gt3()/gt4()
                                   // per referenced ground record group.

  // Wired (see file banner): same discipline as OverlayGt3Gt4 — all three are reached by a
  // direct C call generated by the recorded binary evidence inside the ov_a00 shard, not typed runtime address
  // dispatch, so wired via the overlay's own `A00 tomba::native::declareOverride` table (through the process-global
  // override registry's tomba::native::declareOverride, not a raw table poke).
  static void registerOverrides(Game *game);
};
